### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sedirhaydar**
you can help me plz
i have a project in my school about wavecluster 
I'm having problems

### CODE REVIEW

**Comment by BaiHLiu** [comment]
Oh, I'm really a beginner of data science, but could we talk further?

**Comment by sedirhaydar** [comment]
I'm sorry I didn't see your message
thanks for your reply
I have a project at the university using WaveCluster
I need to upload my data to your project, but it doesn't work

‫في الأربعاء، 11 يناير 2023 في 2:24 م تمت كتابة ما يلي بواسطة ‪BaiHLiu‬‏ <‪
***@***.***‬‏>:‬

**Comment by BaiHLiu** [comment]
Upload your data to my "project"? 
You mean upload some files to this Github repository, or just run my code with your datasets?
If the former, try to Fork my project, and upload your files via web or git-cli.
If the latter, please offer more information.

**Comment by sedirhaydar** [comment]
yes run your code with my datasets


‫في الخميس، 12 يناير 2023 في 4:11 م تمت كتابة ما يلي بواسطة ‪BaiHLiu‬‏ <‪
***@***.***‬‏>:‬

**Comment by sedirhaydar** [comment]
yes iwant run your code with my dataset you can help me


‫في الخميس، 12 يناير 2023 في 4:25 م تمت كتابة ما يلي بواسطة ‪Sader
Hedar1996‬‏ ***@***.***‬‏>:‬

**Pull request closed without merging**
